using UnityEngine;

namespace TK
{
	public class AppTimeZone
	{
		public static string Current { get; private set; }

		[RuntimeInitializeOnLoadMethod]
		private static void InitTimezone ()
		{
			string[] zones = new string[]
			{
			"Africa/Abidjan|GMT",
			"Africa/Khartoum|EAT",
			"Africa/Algiers|CET",
			"Africa/Lagos|WAT",
			"Africa/Maputo|CAT",
			"Africa/Cairo|EET EEST",
			"Africa/Casablanca|WET WEST",
			"Europe/Paris|CET CEST",
			"Africa/Johannesburg|SAST",
			"Africa/Tripoli|EET CET CEST",
			"Africa/Windhoek|WAST WAT",
			"America/Adak|HST HDT",
			"America/Anchorage|AKST AKDT",
			"America/Santo_Domingo|AST",
			"America/Araguaina|BRT BRST",
			"America/Argentina/Buenos_Aires|ART",
			"America/Asuncion|PYST PYT",
			"America/Panama|EST",
			"America/Bahia|BRT BRST",
			"America/Bahia_Banderas|MST CDT CST",
			"America/Fortaleza|BRT",
			"America/Managua|CST",
			"America/Manaus|AMT",
			"America/Bogota|COT",
			"America/Denver|MST MDT",
			"America/Campo_Grande|AMST AMT",
			"America/Cancun|CST CDT EST",
			"America/Caracas|VET",
			"America/Cayenne|GFT",
			"America/Chicago|CST CDT",
			"America/Chihuahua|MST MDT",
			"America/Phoenix|MST",
			"America/Los_Angeles|PST PDT",
			"America/New_York|EST EDT",
			"America/Rio_Branco|AMT ACT",
			"America/Fort_Nelson|PST PDT MST",
			"America/Halifax|AST ADT",
			"America/Godthab|WGT WGST",
			"America/Goose_Bay|AST ADT",
			"America/Grand_Turk|EST EDT AST",
			"America/Guayaquil|ECT",
			"America/Guyana|GYT",
			"America/Havana|CST CDT",
			"America/La_Paz|BOT",
			"America/Lima|PET",
			"America/Mexico_City|CST CDT",
			"America/Metlakatla|PST AKST AKDT",
			"America/Miquelon|PMST PMDT",
			"America/Montevideo|UYST UYT",
			"America/Noronha|FNT",
			"America/North_Dakota/Beulah|MST MDT CST CDT",
			"America/Paramaribo|SRT",
			"America/Port-au-Prince|EST EDT",
			"America/Santiago|CLST CLT",
			"America/Sao_Paulo|BRST BRT",
			"America/Scoresbysund|EGT EGST",
			"America/St_Johns|NST NDT",
			"Antarctica/Casey|CAST AWST",
			"Antarctica/Davis|DAVT DAVT",
			"Antarctica/DumontDUrville|DDUT",
			"Antarctica/Macquarie|AEDT MIST",
			"Antarctica/Mawson|MAWT",
			"Pacific/Auckland|NZDT NZST",
			"Antarctica/Rothera|ROTT",
			"Antarctica/Syowa|SYOT",
			"Antarctica/Troll|UTC CEST",
			"Antarctica/Vostok|VOST",
			"Asia/Baghdad|AST",
			"Asia/Almaty|ALMT",
			"Asia/Amman|EET EEST",
			"Asia/Anadyr|ANAT ANAST ANAT",
			"Asia/Aqtobe|AQTT",
			"Asia/Ashgabat|TMT",
			"Asia/Baku|AZT AZST",
			"Asia/Bangkok|ICT",
			"Asia/Barnaul|+06 +07",
			"Asia/Beirut|EET EEST",
			"Asia/Bishkek|KGT",
			"Asia/Brunei|BNT",
			"Asia/Kolkata|IST",
			"Asia/Chita|YAKT YAKST YAKT IRKT",
			"Asia/Choibalsan|CHOT CHOST",
			"Asia/Shanghai|CST",
			"Asia/Dhaka|BDT",
			"Asia/Damascus|EET EEST",
			"Asia/Dili|TLT",
			"Asia/Dubai|GST",
			"Asia/Dushanbe|TJT",
			"Asia/Gaza|EET EEST",
			"Asia/Hebron|EET EEST",
			"Asia/Hong_Kong|HKT",
			"Asia/Hovd|HOVT HOVST",
			"Asia/Irkutsk|IRKT IRKST IRKT",
			"Europe/Istanbul|EET EEST",
			"Asia/Jakarta|WIB",
			"Asia/Jayapura|WIT",
			"Asia/Jerusalem|IST IDT",
			"Asia/Kabul|AFT",
			"Asia/Kamchatka|PETT PETST PETT",
			"Asia/Karachi|PKT",
			"Asia/Urumqi|XJT",
			"Asia/Kathmandu|NPT",
			"Asia/Khandyga|VLAT VLAST VLAT YAKT YAKT",
			"Asia/Krasnoyarsk|KRAT KRAST KRAT",
			"Asia/Kuala_Lumpur|MYT",
			"Asia/Magadan|MAGT MAGST MAGT MAGT",
			"Asia/Makassar|WITA",
			"Asia/Manila|PHT",
			"Europe/Athens|EET EEST",
			"Asia/Novokuznetsk|KRAT NOVST NOVT NOVT",
			"Asia/Novosibirsk|NOVT NOVST NOVT",
			"Asia/Omsk|OMST OMSST OMST",
			"Asia/Oral|ORAT",
			"Asia/Pyongyang|KST KST",
			"Asia/Qyzylorda|QYZT",
			"Asia/Rangoon|MMT",
			"Asia/Sakhalin|SAKT SAKST SAKT",
			"Asia/Tashkent|UZT",
			"Asia/Seoul|KST",
			"Asia/Singapore|SGT",
			"Asia/Srednekolymsk|MAGT MAGST MAGT SRET",
			"Asia/Tbilisi|GET",
			"Asia/Tehran|IRST IRDT",
			"Asia/Thimphu|BTT",
			"Asia/Tokyo|JST",
			"Asia/Ulaanbaatar|ULAT ULAST",
			"Asia/Ust-Nera|MAGT MAGST MAGT VLAT VLAT",
			"Asia/Vladivostok|VLAT VLAST VLAT",
			"Asia/Yakutsk|YAKT YAKST YAKT",
			"Asia/Yekaterinburg|YEKT YEKST YEKT",
			"Asia/Yerevan|AMT AMST",
			"Atlantic/Azores|AZOT AZOST",
			"Europe/Lisbon|WET WEST",
			"Atlantic/Cape_Verde|CVT",
			"Atlantic/South_Georgia|GST",
			"Atlantic/Stanley|FKST FKT",
			"Australia/Sydney|AEDT AEST",
			"Australia/Adelaide|ACDT ACST",
			"Australia/Brisbane|AEST",
			"Australia/Darwin|ACST",
			"Australia/Eucla|ACWST",
			"Australia/Lord_Howe|LHDT LHST",
			"Australia/Perth|AWST",
			"Pacific/Easter|EASST EAST",
			"Europe/Dublin|GMT IST",
			"Etc/GMT+1|GMT+1",
			"Etc/GMT+10|GMT+10",
			"Etc/GMT+11|GMT+11",
			"Etc/GMT+12|GMT+12",
			"Etc/GMT+2|GMT+2",
			"Etc/GMT+3|GMT+3",
			"Etc/GMT+4|GMT+4",
			"Etc/GMT+5|GMT+5",
			"Etc/GMT+6|GMT+6",
			"Etc/GMT+7|GMT+7",
			"Etc/GMT+8|GMT+8",
			"Etc/GMT+9|GMT+9",
			"Etc/GMT-1|GMT-1",
			"Etc/GMT-10|GMT-10",
			"Etc/GMT-11|GMT-11",
			"Etc/GMT-12|GMT-12",
			"Etc/GMT-13|GMT-13",
			"Etc/GMT-14|GMT-14",
			"Etc/GMT-2|GMT-2",
			"Etc/GMT-3|GMT-3",
			"Etc/GMT-4|GMT-4",
			"Etc/GMT-5|GMT-5",
			"Etc/GMT-6|GMT-6",
			"Etc/GMT-7|GMT-7",
			"Etc/GMT-8|GMT-8",
			"Etc/GMT-9|GMT-9",
			"Etc/UCT|UCT",
			"Etc/UTC|UTC",
			"Europe/Astrakhan|+03 +04",
			"Europe/London|GMT BST",
			"Europe/Chisinau|EET EEST",
			"Europe/Kaliningrad|EET EEST FET",
			"Europe/Minsk|EET EEST FET MSK",
			"Europe/Moscow|MSK MSD MSK",
			"Europe/Samara|SAMT SAMST SAMT",
			"Europe/Simferopol|EET EEST MSK MSK",
			"Pacific/Honolulu|HST",
			"Indian/Chagos|IOT",
			"Indian/Christmas|CXT",
			"Indian/Cocos|CCT",
			"Indian/Kerguelen|TFT",
			"Indian/Mahe|SCT",
			"Indian/Maldives|MVT",
			"Indian/Mauritius|MUT",
			"Indian/Reunion|RET",
			"Pacific/Majuro|MHT",
			"MET|MET MEST",
			"Pacific/Chatham|CHADT CHAST",
			"Pacific/Apia|SST SDT WSDT WSST",
			"Pacific/Bougainville|PGT BST",
			"Pacific/Chuuk|CHUT",
			"Pacific/Efate|VUT",
			"Pacific/Enderbury|PHOT",
			"Pacific/Fakaofo|TKT TKT",
			"Pacific/Fiji|FJST FJT",
			"Pacific/Funafuti|TVT",
			"Pacific/Galapagos|GALT",
			"Pacific/Gambier|GAMT",
			"Pacific/Guadalcanal|SBT",
			"Pacific/Guam|ChST",
			"Pacific/Kiritimati|LINT",
			"Pacific/Kosrae|KOST",
			"Pacific/Marquesas|MART",
			"Pacific/Pago_Pago|SST",
			"Pacific/Nauru|NRT",
			"Pacific/Niue|NUT",
			"Pacific/Norfolk|NFT NFT",
			"Pacific/Noumea|NCT",
			"Pacific/Palau|PWT",
			"Pacific/Pitcairn|PST",
			"Pacific/Pohnpei|PONT",
			"Pacific/Port_Moresby|PGT",
			"Pacific/Rarotonga|CKT",
			"Pacific/Tahiti|TAHT",
			"Pacific/Tarawa|GILT",
			"Pacific/Tongatapu|TOT",
			"Pacific/Wake|WAKT",
			"Pacific/Wallis|WFT",
			"Africa/Bangui|W. Central Africa Standard Time",
			"Africa/Cairo|Egypt Standard Time",
			"Africa/Casablanca|Morocco Standard Time",
			"Africa/Harare|South Africa Standard Time",
			"Africa/Johannesburg|South Africa Standard Time",
			"Africa/Lagos|W. Central Africa Standard Time",
			"Africa/Monrovia|Greenwich Standard Time",
			"Africa/Nairobi|E. Africa Standard Time",
			"Africa/Windhoek|Namibia Standard Time",
			"America/Anchorage|Alaskan Standard Time",
			"America/Argentina/San_Juan|Argentina Standard Time",
			"America/Asuncion|Paraguay Standard Time",
			"America/Bahia|Bahia Standard Time",
			"America/Bogota|SA Pacific Standard Time",
			"America/Buenos_Aires|Argentina Standard Time",
			"America/Caracas|Venezuela Standard Time",
			"America/Cayenne|SA Eastern Standard Time",
			"America/Chicago|Central Standard Time",
			"America/Chihuahua|Mountain Standard Time (Mexico)",
			"America/Cuiaba|Central Brazilian Standard Time",
			"America/Denver|Mountain Standard Time",
			"America/Fortaleza|SA Eastern Standard Time",
			"America/Godthab|Greenland Standard Time",
			"America/Guatemala|Central America Standard Time",
			"America/Halifax|Atlantic Standard Time",
			"America/Indianapolis|US Eastern Standard Time",
			"America/Indiana/Indianapolis|US Eastern Standard Time",
			"America/La_Paz|SA Western Standard Time",
			"America/Los_Angeles|Pacific Standard Time",
			"America/Mexico_City|Mexico Standard Time",
			"America/Montevideo|Montevideo Standard Time",
			"America/New_York|Eastern Standard Time",
			"America/Noronha|UTC-02",
			"America/Phoenix|US Mountain Standard Time",
			"America/Regina|Canada Central Standard Time",
			"America/Santa_Isabel|Pacific Standard Time (Mexico)",
			"America/Santiago|Pacific SA Standard Time",
			"America/Sao_Paulo|E. South America Standard Time",
			"America/St_Johns|Newfoundland Standard Time",
			"America/Tijuana|Pacific Standard Time",
			"Antarctica/McMurdo|New Zealand Standard Time",
			"Atlantic/South_Georgia|UTC-02",
			"Asia/Almaty|Central Asia Standard Time",
			"Asia/Amman|Jordan Standard Time",
			"Asia/Baghdad|Arabic Standard Time",
			"Asia/Baku|Azerbaijan Standard Time",
			"Asia/Bangkok|SE Asia Standard Time",
			"Asia/Beirut|Middle East Standard Time",
			"Asia/Calcutta|India Standard Time",
			"Asia/Colombo|Sri Lanka Standard Time",
			"Asia/Damascus|Syria Standard Time",
			"Asia/Dhaka|Bangladesh Standard Time",
			"Asia/Dubai|Arabian Standard Time",
			"Asia/Irkutsk|North Asia East Standard Time",
			"Asia/Jerusalem|Israel Standard Time",
			"Asia/Kabul|Afghanistan Standard Time",
			"Asia/Kamchatka|Kamchatka Standard Time",
			"Asia/Karachi|Pakistan Standard Time",
			"Asia/Katmandu|Nepal Standard Time",
			"Asia/Kolkata|India Standard Time",
			"Asia/Krasnoyarsk|North Asia Standard Time",
			"Asia/Kuala_Lumpur|Singapore Standard Time",
			"Asia/Kuwait|Arab Standard Time",
			"Asia/Magadan|Magadan Standard Time",
			"Asia/Muscat|Arabian Standard Time",
			"Asia/Novosibirsk|N. Central Asia Standard Time",
			"Asia/Oral|West Asia Standard Time",
			"Asia/Rangoon|Myanmar Standard Time",
			"Asia/Riyadh|Arab Standard Time",
			"Asia/Seoul|Korea Standard Time",
			"Asia/Shanghai|China Standard Time",
			"Asia/Singapore|Singapore Standard Time",
			"Asia/Taipei|Taipei Standard Time",
			"Asia/Tashkent|West Asia Standard Time",
			"Asia/Tbilisi|Georgian Standard Time",
			"Asia/Tehran|Iran Standard Time",
			"Asia/Tokyo|Tokyo Standard Time",
			"Asia/Ulaanbaatar|Ulaanbaatar Standard Time",
			"Asia/Vladivostok|Vladivostok Standard Time",
			"Asia/Yakutsk|Yakutsk Standard Time",
			"Asia/Yekaterinburg|Ekaterinburg Standard Time",
			"Asia/Yerevan|Armenian Standard Time",
			"Atlantic/Azores|Azores Standard Time",
			"Atlantic/Cape_Verde|Cape Verde Standard Time",
			"Atlantic/Reykjavik|Greenwich Standard Time",
			"Australia/Adelaide|Cen. Australia Standard Time",
			"Australia/Brisbane|E. Australia Standard Time",
			"Australia/Darwin|AUS Central Standard Time",
			"Australia/Hobart|Tasmania Standard Time",
			"Australia/Perth|W. Australia Standard Time",
			"Australia/Sydney|AUS Eastern Standard Time",
			"Etc/GMT|UTC",
			"Etc/GMT+11|UTC-11",
			"Etc/GMT+12|Dateline Standard Time",
			"Etc/GMT+2|UTC-02",
			"Etc/GMT-12|UTC+12",
			"Europe/Amsterdam|W. Europe Standard Time",
			"Europe/Athens|GTB Standard Time",
			"Europe/Belgrade|Central Europe Standard Time",
			"Europe/Berlin|W. Europe Standard Time",
			"Europe/Brussels|Romance Standard Time",
			"Europe/Budapest|Central Europe Standard Time",
			"Europe/Dublin|GMT Standard Time",
			"Europe/Helsinki|FLE Standard Time",
			"Europe/Istanbul|GTB Standard Time",
			"Europe/Kiev|FLE Standard Time",
			"Europe/London|GMT Standard Time",
			"Europe/Minsk|E. Europe Standard Time",
			"Europe/Moscow|Russian Standard Time",
			"Europe/Paris|Romance Standard Time",
			"Europe/Sarajevo|Central European Standard Time",
			"Europe/Warsaw|Central European Standard Time",
			"Indian/Mauritius|Mauritius Standard Time",
			"Pacific/Apia|Samoa Standard Time",
			"Pacific/Auckland|New Zealand Standard Time",
			"Pacific/Fiji|Fiji Standard Time",
			"Pacific/Guadalcanal|Central Pacific Standard Time",
			"Pacific/Guam|West Pacific Standard Time",
			"Pacific/Honolulu|Hawaiian Standard Time",
			"Pacific/Pago_Pago|UTC-11",
			"Pacific/Port_Moresby|West Pacific Standard Time",
			"Pacific/Tongatapu|Tonga Standard Time",
			};

			Current = "Etc/GMT";
			string currentTimeZoneName = System.TimeZone.CurrentTimeZone.StandardName;
			string[] data = new string[0];
			int zoneCount = zones.Length;
			for (int i = 0; i < zoneCount; i++)
			{
				data = zones[i].Split ('|');
				if (data[1].Contains (currentTimeZoneName))
				{
					Current = data[0];
					break;
				}
			}

			zones = null;
			data = null;
		}
	}
}
